//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "if"
 * f1 -> "("
 * f2 -> Comparison()
 * f3 -> ")"
 * f4 -> "{"
 * f5 -> ( Sentencia() )+
 * f6 -> "}"
 * f7 -> ( "else" "{" SentenciaMuchas() "}" )?
 */
public class SentenciaIf implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Comparison f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeList f5;
   public NodeToken f6;
   public NodeOptional f7;

   public SentenciaIf(NodeToken n0, NodeToken n1, Comparison n2, NodeToken n3, NodeToken n4, NodeList n5, NodeToken n6, NodeOptional n7) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
   }

   public SentenciaIf(Comparison n0, NodeList n1, NodeOptional n2) {
      f0 = new NodeToken("if");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
      f4 = new NodeToken("{");
      f5 = n1;
      f6 = new NodeToken("}");
      f7 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

